version: '3.8'

services:
  aries-cloudagent-issuer:
    image: stelladim/aries-cloudagent-amd64
    environment:
      ISSUER_ADMIN_PORT: ${ISSUER_ADMIN_PORT}
      ISSUER_PORT: ${ISSUER_PORT}
      ISSUER_IP: ${ISSUER_IP}
      LABEL: ${LABEL}
      LEDGER_IP: ${LEDGER_IP}
      LEDGER_PORT: ${LEDGER_PORT}
      WALLET_NAME: ${WALLET_NAME}
      WALLET_KEY: ${WALLET_KEY}
      TAILS_SERVER_IP: ${TAILS_SERVER_IP}
      TAILS_SERVER_PORT: ${TAILS_SERVER_PORT}
    container_name: aries-cloudagent-issuer
    command:
      - start
      - --admin
      - '0.0.0.0'
      - '${ISSUER_ADMIN_PORT}'
      - --inbound-transport
      - http
      - '0.0.0.0'
      - '${ISSUER_PORT}'
      - --endpoint
      - 'http://${ISSUER_IP}:${ISSUER_PORT}'
      - --outbound-transport
      - http
      - --label
      - '${LABEL}'
      - --admin-insecure-mode
      - --public-invites
      - --auto-ping-connection
      - --auto-accept-invites
      - --auto-accept-requests
      - --auto-respond-credential-proposal
      - --genesis-url
      - 'http://${LEDGER_IP}:${LEDGER_PORT}/genesis'
      - --preserve-exchange-records
      - --auto-provision
      - --emit-new-didcomm-prefix
      - --wallet-type
      - 'askar'
      - --wallet-name
      - '${WALLET_NAME}'
      - --wallet-key
      - '${WALLET_KEY}'
      - --tails-server-base-url
      - 'http://${TAILS_SERVER_IP}:${TAILS_SERVER_PORT}'
    ports:
      - "${ISSUER_PORT}:${ISSUER_PORT}"
      - "${ISSUER_ADMIN_PORT}:${ISSUER_ADMIN_PORT}"
    stdin_open: true  # equivalent to -it
    tty: true         # optional for interactivity
    restart: always   # ensures the service is always running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${ISSUER_IP}:${ISSUER_ADMIN_PORT}/status/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  issuer:
    build:
      context: .
      dockerfile: Dockerfile
    image: issuer-image
    environment:
      ISSUER_ADMIN_PORT: ${ISSUER_ADMIN_PORT}
      ISSUER_IP: ${ISSUER_IP}
      LABEL: ${LABEL}
      LEDGER_IP: ${LEDGER_IP}
      LEDGER_PORT: ${LEDGER_PORT}
      ISSUER_FastAPI_PORT: ${ISSUER_FastAPI_PORT}
    container_name: issuer
    restart: on-failure
    ports:
      - "${ISSUER_FastAPI_PORT}:${ISSUER_FastAPI_PORT}"
    depends_on:
      aries-cloudagent-issuer:
        condition: service_healthy  # Wait for aries-cloudagent-issuer to be healthy.      
    stdin_open: true  # equivalent to -it
    tty: true         # optional for interactivity

