version: '3.8'

services:
  aries-cloudagent-verifier:
    image: stelladim/aries-cloudagent-amd64
    environment:
      VERIFIER_ADMIN_PORT: ${VERIFIER_ADMIN_PORT}
      VERIFIER_PORT: ${VERIFIER_PORT}
      VERIFIER_IP: ${VERIFIER_IP}
      LABEL: ${LABEL}
      LEDGER_IP: ${LEDGER_IP}
      LEDGER_PORT: ${LEDGER_PORT}
      WALLET_NAME: ${WALLET_NAME}
      WALLET_KEY: ${WALLET_KEY}
    container_name: aries-cloudagent-verifier
    command:
      - start
      - --admin
      - '0.0.0.0'
      - '${VERIFIER_ADMIN_PORT}'
      - --inbound-transport
      - http
      - '0.0.0.0'
      - '${VERIFIER_PORT}'
      - --endpoint
      - 'http://${VERIFIER_IP}:${VERIFIER_PORT}'
      - --outbound-transport
      - http
      - --label
      - '${LABEL}'
      - --admin-insecure-mode
      - --public-invites
      - --auto-ping-connection
      - --auto-accept-invites
      - --auto-accept-requests
      - --auto-verify-presentation
      - --genesis-url
      - 'http://${LEDGER_IP}:${LEDGER_PORT}/genesis'
      - --preserve-exchange-records
      - --auto-provision
      - --emit-new-didcomm-prefix
      - --wallet-type
      - 'askar'
      - --wallet-name 
      - '${WALLET_NAME}'
      - --wallet-key
      - '${WALLET_KEY}'
    ports:
      - "${VERIFIER_PORT}:${VERIFIER_PORT}"
      - "${VERIFIER_ADMIN_PORT}:${VERIFIER_ADMIN_PORT}"
    stdin_open: true  # equivalent to -it
    tty: true         # optional for interactivity
    restart: always   # ensures the service is always running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${VERIFIER_IP}:${VERIFIER_ADMIN_PORT}/status/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  verifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: verifier-image
    environment:
      VERIFIER_ADMIN_PORT: ${VERIFIER_ADMIN_PORT}
      VERIFIER_IP: ${VERIFIER_IP}
      LABEL: ${LABEL}
      LEDGER_IP: ${LEDGER_IP}
      LEDGER_PORT: ${LEDGER_PORT}
      ISSUER_IP: ${ISSUER_IP}
      ISSUER_PORT: ${ISSUER_PORT}
      VERIFIER_FastAPI_PORT: ${VERIFIER_FastAPI_PORT}
    container_name: verifier
    restart: on-failure
    ports:
      - "${VERIFIER_FastAPI_PORT}:${VERIFIER_FastAPI_PORT}"
    depends_on:
      aries-cloudagent-verifier:
        condition: service_healthy  # Wait for aries-cloudagent-verifier to be healthy.      
    stdin_open: true  # equivalent to -it
    tty: true         # optional for interactivity

